remote_theme: jekyll-theme-plain/jekyll-theme-plain

# lang: en
# color_scheme: false # disables color scheme sync
title: Your awesome title
# url: https://USERNAME.github.io
# basename: 
# canonical_url: false # disables canonical URLs
# license_url: 

#
# To use a style sheet, place it in _includes/default.css (or any) and uncomment the following lines:
#

# stylesheets:
#   - default.css
